export { default as Header } from './Header.vue'
export { default as Footer } from './Footer.vue'
export { default as Main } from './Main.vue'
export { default as Card } from './Card.vue'
export { default as HelloName } from './HelloName.vue'
export { default as CounterButton } from './CounterButton.vue'
export { default as ToggleSwitch } from './ToggleSwitch.update.vue'
export { default as Input } from './Input.vue'